### ISSUE TITLE
Issue 6: Training the model 

### ISSUE THREAD

**Issue by VirginiaWanjiru** [VirginiaWanjiru/BIProject-Crop-Prediction-Analytics#5]
- [x] Data splitting 
- [x] Bootstrapping 
- [x] Resampling
- [x] Cross-validation(Basic,repeated or LOOCV)
- [x] Model training for either classification, Regression, Association, Clustering 
- [x] Model performance comparison using resamples( for classification and regression)

**Comment by VirginiaWangAngA** [comment]
Done with Training the model
