### ISSUE TITLE
Issue 7: For Milestone 4 : Hyper-Parameter Tuning and Ensembles (Lab9-11)

### ISSUE THREAD

**Issue by VirginiaWanjiru** [VirginiaWanjiru/BIProject-Crop-Prediction-Analytics#6]
- [x] Random/Grid/ Manual Search
- [x] Bagging/Boosting/Stacking Ensembles (if applicable)

**Comment by VirginiaWangAngA** [comment]
Done Issue 7.Have not included Bagging/Bootstrap aggregation/Stacking Ensembles
